task:
  name: "FreeBSD 13"
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-0-snap
  deps_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - env ASSUME_ALWAYS_YES=yes pkg update -f
    - env ASSUME_ALWAYS_YES=yes pkg remove -y python27 python2 python37
    - env ASSUME_ALWAYS_YES=yes pkg install -y python3 python39 py39-polib py39-lxml
    - env ASSUME_ALWAYS_YES=yes pkg install -y gmake pkgconf poco cppunit autotools coreutils git bash npm png pango
    - mkdir libreoffice-src
    - cd libreoffice-src
    - fetch https://github.com/freeonlineoffice/online/releases/download/Core-LibreOffice-Assets/LibreOfficeKit-includes-lo-7.5-alpha.tar.gz
    - tar -xzf LibreOfficeKit-includes-lo-7.5-alpha.tar.gz
  build_script:
    - mkdir .git/hooks
    - pw useradd -n lool -d /tmp/loolhome -m
    - chmod -R o+rwx ./
    - su -m lool -c './autogen.sh'
    - 'su -m lool -c ''env HOME=/tmp/loolhome MAKE=gmake
        CPPFLAGS="-isystem /usr/local/include" CFLAGS="-I/usr/local/include"
        CXXFLAGS="-I/usr/local/include" LDFLAGS=-L/usr/local/lib ./configure
        --with-lo-path=/usr/local/lib/libreoffice/
        --with-lokit-path=./libreoffice-src/include
        --disable-seccomp --disable-setcap --enable-debug'' '
    - su -m lool -c 'env HOME=/tmp/loolhome gmake -j`sysctl -n hw.ncpu`'
    - chown root ./loolmount
    - chmod +s ./loolmount
  test_script:
#    - su -m lool -c 'env HOME=/tmp/loolhome gmake check'
